branch-defaults:
  develop:
    environment: production
    group_suffix: null
global:
  application_name: imfo
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: imfo-dev
  repository: null
  sc: git
  workspace_type: Application
